#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

APP_PID=""
MONITOR_PID=""
LOG_FILE="${TMPDIR:-/tmp}/openstream-issue-105.log"
RESULTS_FILE="${TMPDIR:-/tmp}/openstream-issue-105-$(date +%Y%m%d-%H%M%S).md"
UI_RESULT="not run"
INSERTION_RESULT="not run"
LOCAL_RESULT="not run"
LATENCY_RESULT="not run"
LISTENERS=""
CONNECTIONS=""
LATENCIES=()

stop_app() {
  if [[ -n "$APP_PID" ]] && kill -0 "$APP_PID" 2>/dev/null; then
    kill "$APP_PID" 2>/dev/null || true
    wait "$APP_PID" 2>/dev/null || true
  fi
  APP_PID=""
}

start_app() {
  : > "$LOG_FILE"
  npm start > "$LOG_FILE" 2>&1 &
  APP_PID=$!
  sleep 3
  if ! kill -0 "$APP_PID" 2>/dev/null; then
    warn "OpenStream exited during startup. Read $LOG_FILE"
    return 1
  fi
}

wait_for_listener() {
  local port="$1" waited=0
  while ! lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; do
    if (( waited >= 120 )); then
      warn "Nothing listened on port $port after 120 seconds. Read $LOG_FILE"
      return 1
    fi
    sleep 2
    waited=$((waited + 2))
  done
}

record_connections() {
  local output="$1" pid
  : > "$output"
  while true; do
    for pid in $(lsof -tiTCP:8178 -sTCP:LISTEN 2>/dev/null; lsof -tiTCP:8179 -sTCP:LISTEN 2>/dev/null); do
      lsof -nP -a -p "$pid" -iTCP 2>/dev/null >> "$output" || true
    done
    sleep 0.1
  done
}

cleanup_wizard() {
  if [[ -n "$MONITOR_PID" ]]; then
    kill "$MONITOR_PID" 2>/dev/null || true
    wait "$MONITOR_PID" 2>/dev/null || true
  fi
  stop_app
}
trap cleanup_wizard EXIT INT TERM

banner "OpenStream end-to-end verification"

stage "Check and build the app"
if [[ "$(uname -s)" != "Darwin" || "$(uname -m)" != "arm64" ]]; then
  warn "This check requires an Apple Silicon Mac. Found $(uname -s) $(uname -m)."
  exit 1
fi
for command_name in npm cmake git curl lsof open spctl; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    warn "Missing required command: $command_name"
    exit 1
  fi
done
if [[ ! -x node_modules/electron/dist/Electron.app/Contents/MacOS/Electron || \
      ! -x resources/bin/whisper-server || ! -x resources/bin/llama-server || \
      ! -x resources/bin/hotkey-helper || ! -x resources/bin/accessibility-helper || \
      ! -f resources/models/ggml-base.en.bin || \
      ! -f resources/models/SmolLM2-1.7B-Instruct-Q4_K_M.gguf ]]; then
  say "The built helpers or pinned model artifacts are missing. npm install builds or fetches them."
  warn "The first install downloads about 1.15 GB. Matching cached artifacts are reused."
  if confirm "Run npm install now?"; then
    npm install
  else
    exit 1
  fi
fi
GATEKEEPER_OUTPUT=$(spctl --assess --type execute --verbose=4 node_modules/electron/dist/Electron.app 2>&1 || true)
if printf '%s\n' "$GATEKEEPER_OUTPUT" | grep -Eqi 'revoked|malware'; then
  warn "Gatekeeper rejected this Electron runtime as revoked or malicious."
  printf '%s\n' "$GATEKEEPER_OUTPUT"
  say "Do not bypass Gatekeeper. Update Electron before continuing."
  exit 1
fi
say "Electron $(node -p 'require("electron/package.json").version') is present and is not revoked by Gatekeeper."
say "Running the automated checks before touching macOS permissions."
npm test
npm run typecheck
say "Automated checks passed."
pause "Continue to app startup?"

stage "Launch and grant macOS permissions"
start_app
say "OpenStream needs Microphone, Input Monitoring, and Accessibility access."
step "If macOS asks for Microphone access, allow it."
open_url "x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone"
step "Enable Terminal for this source run. If macOS shows Electron or OpenStream instead, enable that entry."
pause "Press Enter after checking Microphone access."
open_url "x-apple.systempreferences:com.apple.preference.security?Privacy_ListenEvent"
step "Enable Terminal for this source run. If macOS shows Electron or OpenStream instead, enable that entry."
pause "Press Enter after checking Input Monitoring access."
open_url "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"
step "Enable Terminal for this source run. If macOS shows Electron or OpenStream instead, enable that entry."
pause "Press Enter after checking Accessibility access."
step "A source run may never add Electron or OpenStream because macOS attributes its helpers to Terminal."
pause "Press Enter after all three permissions are enabled. The wizard will relaunch OpenStream."
stop_app
start_app
say "Waiting for both resident model servers. A cold Metal startup may take 20 seconds."
wait_for_listener 8178
wait_for_listener 8179
say "Both model servers are listening."

stage "Check global push-to-talk feedback"
open -a TextEdit
step "Click inside a new TextEdit document. Keep OpenStream unfocused."
step "Hold Control+Option+D and speak for two or three seconds."
step "While holding the keys, confirm the tray shows recording, the overlay is visible, and its sound meter moves with your voice."
step "Release the keys and confirm the tray shows transcribing before returning to idle."
if confirm "Did the global hotkey, real microphone, tray, overlay, and sound meter all work?"; then
  UI_RESULT="pass"
else
  UI_RESULT="fail"
  warn "The UI boundary failed. Keep going so the report captures the other checks."
fi

stage "Check one atomic native insertion"
open -a TextEdit
say "Use this unique three-sentence phrase:"
note "Atomic amber river. Local models stay home. This text appears one time."
step "Place the cursor on an empty line in TextEdit."
step "Hold Control+Option+D, dictate the phrase, then release."
step "Wait for insertion. Do not paste or type any correction."
if confirm "Did one finished block appear exactly once, with no provisional text or later revision?"; then
  INSERTION_RESULT="pass"
else
  INSERTION_RESULT="fail"
  warn "Atomic insertion failed. Details in $LOG_FILE may explain why."
fi

stage "Check localhost-only model processing"
LISTENERS=$(lsof -nP -iTCP -sTCP:LISTEN | awk '$9 ~ /:8178$|:8179$/ { print }')
printf '%s\n' "$LISTENERS"
LISTENER_COUNT=$(printf '%s\n' "$LISTENERS" | awk 'NF { count++ } END { print count + 0 }')
if [[ "$LISTENER_COUNT" -ne 2 ]] || \
   ! printf '%s\n' "$LISTENERS" | awk 'NF && $9 !~ /^127\.0\.0\.1:817[89]$/ { bad=1 } END { exit bad }'; then
  LOCAL_RESULT="fail"
  warn "A model listener is not bound only to 127.0.0.1."
else
  CONNECTION_FILE=$(mktemp)
  record_connections "$CONNECTION_FILE" &
  MONITOR_PID=$!
  open -a TextEdit
  step "Run one more dictation in TextEdit while the wizard samples model-server connections."
  pause "Press Enter after the text arrives."
  kill "$MONITOR_PID" 2>/dev/null || true
  wait "$MONITOR_PID" 2>/dev/null || true
  MONITOR_PID=""
  CONNECTIONS=$(sort -u "$CONNECTION_FILE")
  rm -f "$CONNECTION_FILE"
  SAMPLED_CONNECTION_COUNT=$(printf '%s\n' "$CONNECTIONS" | awk '$0 ~ /TCP/ && $9 ~ /->/ { count++ } END { print count + 0 }')
  if [[ "$SAMPLED_CONNECTION_COUNT" -eq 0 ]]; then
    LOCAL_RESULT="fail"
    warn "No active model connection was sampled. Repeat this stage with a longer dictation."
  elif printf '%s\n' "$CONNECTIONS" | awk '$0 ~ /TCP/ && $9 ~ /->/ && $9 !~ /^127\.0\.0\.1:[0-9]+->127\.0\.0\.1:/ { bad=1 } END { exit bad }'; then
    LOCAL_RESULT="pass"
    say "Both listeners and sampled model traffic stayed on 127.0.0.1."
  else
    LOCAL_RESULT="fail"
    warn "The model processes showed a non-loopback TCP connection."
  fi
fi

stage "Measure the dictation latency budget"
LATENCY_LINE_START=$(wc -l < "$LOG_FILE")
say "Run three warm dictations in TextEdit. Wait for each insertion before starting the next."
for run in 1 2 3; do
  step "Dictation $run of 3: hold Control+Option+D, speak one sentence, release, and wait for insertion."
  pause "Press Enter after dictation $run arrives."
done
while IFS= read -r value; do
  LATENCIES+=("$value")
done < <(tail -n +$((LATENCY_LINE_START + 1)) "$LOG_FILE" | grep 'release-to-insertion:' | tail -n 3 | sed -E 's/.*release-to-insertion: ([0-9.]+)ms.*/\1/')
if [[ "${#LATENCIES[@]}" -ne 3 ]]; then
  LATENCY_RESULT="fail"
  warn "Expected three timing records, found ${#LATENCIES[@]}. Read $LOG_FILE"
else
  LATENCY_RESULT="pass"
  for value in "${LATENCIES[@]}"; do
    say "Measured ${value}ms"
    if ! awk -v value="$value" 'BEGIN { exit !(value < 1000) }'; then
      LATENCY_RESULT="fail"
    fi
  done
  if [[ "$LATENCY_RESULT" == "pass" ]]; then
    say "All three warm dictations stayed below 1000ms."
  else
    warn "At least one warm dictation exceeded the 1000ms budget."
  fi
fi

stage "Write and optionally post the report"
{
  printf '# OpenStream issue #105 manual verification\n\n'
  printf -- '- Date: `%s`\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf -- '- Commit: `%s`\n' "$(git rev-parse HEAD)"
  printf -- '- macOS: `%s`\n' "$(sw_vers -productVersion)"
  printf -- '- Architecture: `%s`\n\n' "$(uname -m)"
  printf '## Results\n\n'
  printf -- '- Global hotkey, real microphone, tray, overlay, and sound meter: **%s**\n' "$UI_RESULT"
  printf -- '- One atomic insertion into TextEdit: **%s**\n' "$INSERTION_RESULT"
  printf -- '- Localhost-only model listeners and sampled traffic: **%s**\n' "$LOCAL_RESULT"
  printf -- '- Three warm release-to-insertion measurements below 1000ms: **%s**\n' "$LATENCY_RESULT"
  if (( ${#LATENCIES[@]} )); then
    printf '  - Measurements: `%s ms`\n' "${LATENCIES[*]}"
  fi
  printf '\n## Listener evidence\n\n```text\n%s\n```\n' "$LISTENERS"
  printf '\n## Sampled model connections\n\n```text\n%s\n```\n' "$CONNECTIONS"
  printf '\nThe wizard log is at `%s` on the test machine and contains dictated text. Delete it when it is no longer needed.\n' "$LOG_FILE"
} > "$RESULTS_FILE"
say "Wrote $RESULTS_FILE"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 && \
   confirm "Post this report as a comment on Nabzx/openstream issue #105?"; then
  gh issue comment 105 --repo Nabzx/openstream --body-file "$RESULTS_FILE"
else
  note "Post it later with: gh issue comment 105 --repo Nabzx/openstream --body-file $RESULTS_FILE"
fi

finish
say "Verification report: $RESULTS_FILE"
say "Application log: $LOG_FILE"
